title = "Dimitris Zorbas"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsUseClasses = true
DisqusShortname = "zorbash-blog"

copyright = "All rights reserved - 2018"
theme = "hockus2"
baseurl = "https://zorbash.com/"

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 100

[params]
  description = "Code spells, smells and sourcery"
  metaDescription = "Blog about programming of Dimitris Zorbas. Topics: Ruby, Elixir, Erlang, JavaScript, Linux"
  hideHUGOSupport = true
  author = "Dimitris Zorbas"
  bio = "Brave sourcerer, engineer and open-source addict"
  authorwebsite = "https://zorbash.com"
  githubName = "zorbash"
  twitterName = "_zorbash"
  cover = "images/road.jpg"
  logo = "images/zorbash.jpg"
  googleAnalyticsUserId = "UA-89343761-1"

[site]
  DisqusShortname = "zorbash-blog"

[params.social]
  twitter = "_zorbash"

[markup.goldmark.renderer]
  unsafe = true
